#!/usr/bin/env python3
"""
generate_blog_data.py

Scans every .html file in /blog/ at the repo root, pulls metadata straight
out of each page's <meta> tags (the same tags your post template already
writes), and regenerates assets/js/blog-data.js from scratch.

No manual editing of blog-data.js required — just drop a new post file
into /blog/ and this script (run by the GitHub Action) picks it up.

Run locally for testing:  python3 generate_blog_data.py
"""

import re
import json
import glob
import os

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
BLOG_DIR = os.path.join(REPO_ROOT, "blog")
OUTPUT_PATH = os.path.join(REPO_ROOT, "assets", "js", "blog-data.js")

# Category -> emoji fallback (used only if a post lacks a recognizable
# icon convention; edit/extend freely).
CATEGORY_ICONS = {
    "ai tools": "🧑‍💻",
    "guide": "⚙️",
    "automation": "🤖",
    "founders": "🚀",
    "hiring": "📋",
    "beginner's guide": "🔰",
    "education": "💡",
}
DEFAULT_ICON = "📄"


def meta(html, name=None, prop=None):
    """Return the content= value of a <meta name="..."> or <meta property="...">."""
    attr, value = ("name", name) if name else ("property", prop)
    pattern = rf'<meta\s+{attr}=["\']{re.escape(value)}["\']\s+content=["\'](.*?)["\']'
    m = re.search(pattern, html, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else None


def first_title_tag(html):
    m = re.search(r"<title>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else None


def extract_read_mins(html):
    # JSON-LD "timeRequired": "PT12M"
    m = re.search(r'"timeRequired"\s*:\s*"PT(\d+)M"', html)
    if m:
        return int(m.group(1))
    return 8  # sane fallback


def extract_image_path(image_url):
    """Convert an absolute og:image URL to the site-relative path blog.html expects."""
    if not image_url:
        return ""
    marker = "assets/images/"
    idx = image_url.find(marker)
    return image_url[idx:] if idx != -1 else image_url


def build_entry(filepath):
    slug = os.path.splitext(os.path.basename(filepath))[0]
    with open(filepath, "r", encoding="utf-8") as f:
        html = f.read()

    title = meta(html, prop="og:title") or first_title_tag(html) or slug
    excerpt = meta(html, name="description") or meta(html, prop="og:description") or ""
    category = meta(html, prop="article:section") or "Guide"
    author = meta(html, name="author") or "Flexora.Ai Team"
    date_raw = meta(html, prop="article:published_time") or ""
    date = date_raw[:10] if date_raw else ""
    image = extract_image_path(meta(html, prop="og:image"))
    image_alt_match = re.search(
        r'<img[^>]+src=["\'][^"\']*' + re.escape(os.path.basename(image)) + r'["\'][^>]*alt=["\'](.*?)["\']',
        html, re.IGNORECASE
    ) if image else None
    image_alt = image_alt_match.group(1) if image_alt_match else title
    read_mins = extract_read_mins(html)
    icon = CATEGORY_ICONS.get(category.lower(), DEFAULT_ICON)

    return {
        "slug": slug,
        "title": title,
        "excerpt": excerpt,
        "category": category,
        "author": author,
        "date": date,
        "readMins": read_mins,
        "image": image,
        "imageAlt": image_alt,
        "icon": icon,
        "published": True,
    }


def js_string(value):
    return json.dumps(value, ensure_ascii=False)


def render_entry(entry, is_featured):
    return (
        "  {\n"
        f"    slug: {js_string(entry['slug'])},\n"
        f"    title: {js_string(entry['title'])},\n"
        f"    excerpt: {js_string(entry['excerpt'])},\n"
        f"    category: {js_string(entry['category'])},\n"
        f"    author: {js_string(entry['author'])},\n"
        f"    date: {js_string(entry['date'])},\n"
        f"    readMins: {entry['readMins']},\n"
        f"    image: {js_string(entry['image'])},\n"
        f"    imageAlt: {js_string(entry['imageAlt'])},\n"
        f"    icon: {js_string(entry['icon'])},\n"
        f"    published: true,\n"
        f"    featured: {'true' if is_featured else 'false'}\n"
        "  }"
    )


def main():
    files = sorted(glob.glob(os.path.join(BLOG_DIR, "*.html")))
    if not files:
        print("No files found in /blog/ — nothing to do.")
        return

    entries = [build_entry(fp) for fp in files]
    # Newest date first; entries with no parseable date sort last.
    entries.sort(key=lambda e: e["date"] or "0000-00-00", reverse=True)

    newest_slug = entries[0]["slug"] if entries else None
    rendered = [render_entry(e, e["slug"] == newest_slug) for e in entries]

    header = (
        "/* Flexora.Ai — blog post data.\n"
        "   AUTO-GENERATED by .github/scripts/generate_blog_data.py — do not edit by hand.\n"
        "   To add a post: drop the new file into /blog/, push, and the GitHub Action\n"
        "   regenerates this file automatically. To hide a post without deleting the\n"
        "   file, edit its `published` meta manually here (will be overwritten on next\n"
        "   push — for a permanent hide, remove/rename the file in /blog/ instead).\n"
        "   ========================================================================= */\n\n"
    )
    content = header + "const BLOG_POSTS = [\n" + ",\n".join(rendered) + "\n];\n"

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Wrote {len(entries)} posts to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
