/* Flexora.Ai — auto-generated by scripts/update_blog_data.py
   DO NOT edit BLOG_POSTS by hand — add/remove files in /blog/ instead,
   each with an <!-- FX:POST ... --> block, and push. This file rewrites
   itself automatically. blogCardHTML() and formatDate() below are safe
   to hand-edit if you want to change how a card looks. */

const BLOG_POSTS = [
  { slug:"rank-ai-tool-page-2026", title:"How to actually rank an AI tool page in 2026", category:"SEO", icon:"📈", image:"assets/images/blog/rank-ai-tool-page-2026.webp", imageAlt:"How to actually rank an AI tool page in 2026", excerpt:"SEO playbook — publishing soon.", readMins:10, date:"2026-10-01", published:false, featured:false, author:"Prashant Lalwani" },
  { slug:"ai-image-tools-tested", title:"We tested five AI image tools — here's what stood out", category:"Review", icon:"🎨", image:"assets/images/blog/ai-image-tools-tested.webp", imageAlt:"We tested five AI image tools — here's what stood out", excerpt:"Hands-on review — publishing soon.", readMins:9, date:"2026-09-24", published:false, featured:false, author:"Prashant Lalwani" },
  { slug:"content-pipeline-free-tools", title:"Build a full content pipeline with three free-tier tools", category:"Workflow", icon:"🔗", image:"assets/images/blog/content-pipeline-free-tools.webp", imageAlt:"Build a full content pipeline with three free-tier tools", excerpt:"Step-by-step workflow — publishing soon.", readMins:5, date:"2026-09-17", published:false, featured:false, author:"Prashant Lalwani" },
  { slug:"ai-tools-for-small-business-marketing", title:"7 AI Tools for Small Business Marketing (Without a Marketing Budget)", category:"Guide", icon:"📣", image:"assets/images/blog/ai-tools-for-small-business-marketing.webp", imageAlt:"7 AI Tools for Small Business Marketing (Without a Marketing Budget)", excerpt:"No agency, no marketing hire, no problem — here's what to use for content, ad copy, product photos, social video, SEO and email.", readMins:8, date:"2026-09-01", published:true, featured:false, author:"Prashant Lalwani" },
  { slug:"scriptly-vs-best-ai-writing-software-comparison", title:"Scriptly vs. the best AI writing software: which one should you use?", category:"Comparison", icon:"⚖️", image:"assets/images/blog/scriptly-vs-best-ai-writing-software-comparison.webp", imageAlt:"Scriptly vs. the best AI writing software: which one should you use?", excerpt:"We compared Scriptly against Jasper, Copy.ai, Writesonic and Rytr on price, output quality and ease of use to find who actually wins.", readMins:7, date:"2026-08-30", published:true, featured:false, author:"Prashant Lalwani" },
  { slug:"free-vs-paid-ai-tools", title:"Free vs. paid AI tools: when is it actually worth upgrading?", category:"Guide", icon:"💳", image:"assets/images/blog/free-vs-paid-ai-tools.webp", imageAlt:"Free vs. paid AI tools: when is it actually worth upgrading?", excerpt:"A practical framework for deciding when a free plan is genuinely limiting you, versus when upgrading just adds cost.", readMins:7, date:"2026-08-25", published:true, featured:false, author:"Prashant Lalwani" },
  { slug:"beginners-guide-ai-coding-assistant", title:"A beginner's guide to picking your first AI coding assistant", category:"Guide", icon:"💻", image:"assets/images/blog/beginners-guide-ai-coding-assistant.webp", imageAlt:"A beginner's guide to picking your first AI coding assistant", excerpt:"What actually matters when you're choosing between AI coding tools — and the four questions that narrow the field fast.", readMins:8, date:"2026-08-20", published:true, featured:false, author:"Prashant Lalwani" },
];

function formatDate(d){
  return new Date(d + 'T00:00:00').toLocaleDateString('en-US', {month:'short', day:'numeric', year:'numeric'});
}

// Escapes text that gets inserted into HTML via innerHTML/template strings,
// so a title or excerpt containing <, >, &, or " can never break card markup
// or be mistaken for real HTML. Used for anything NOT already inside an
// HTML attribute (those use their own quote-only escaping below).
function escapeHtml(str){
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function blogCardHTML(p, prefix){
  prefix = prefix || '';
  const dateLabel = formatDate(p.date);
  const safeAlt = escapeHtml(p.imageAlt || p.title).replace(/"/g, '&quot;');
  const safeTitle = escapeHtml(p.title);
  const safeExcerpt = escapeHtml(p.excerpt);
  const safeCategory = escapeHtml(p.category.toUpperCase());
  // NOTE: this fallback markup ends up INSIDE a double-quoted onerror="..."
  // HTML attribute, so it must use single quotes for its own attribute
  // (class='...') — double quotes here would prematurely close onerror
  // and break the tag.
  const fallbackIcon = `<span class='blog-thumb-icon'>${p.icon}</span>`;
  const thumbInner = p.image
    ? `<img src="${prefix}${p.image}" alt="${safeAlt}" loading="lazy" onerror="this.parentElement.innerHTML='${fallbackIcon.replace(/'/g, "\\'")}';"/>`
    : fallbackIcon;

  const safeAuthor = escapeHtml(p.author || 'Prashant Lalwani');
  const metaLine = p.published
    ? `${p.readMins} min read · ${dateLabel} · <span class="blog-byline">${safeAuthor}</span>`
    : `${p.readMins} min read · ${dateLabel} · Coming soon`;

  const inner = `
    <div class="blog-thumb">${thumbInner}</div>
    <div class="blog-body">
      <span class="blog-cat">${safeCategory}</span>
      <h4>${safeTitle}</h4>
      <p class="blog-excerpt">${safeExcerpt}</p>
      <div class="blog-meta">${metaLine}</div>
    </div>`;

  if (!p.published) {
    return `<div class="blog-card blog-card-disabled">${inner}</div>`;
  }
  return `<a class="blog-card" href="${prefix}blog/${p.slug}.html">${inner}</a>`;
}
