/* Flexora.Ai — auto-generated by scripts/update_blog_data.py
   DO NOT edit BLOG_POSTS by hand — add/remove files in /blog/ instead,
   each with an <!-- FX:POST ... --> block, and push. This file rewrites
   itself automatically. blogCardHTML() and formatDate() below are safe
   to hand-edit if you want to change how a card looks. */

const BLOG_POSTS = [
];

function formatDate(d){
  return new Date(d + 'T00:00:00').toLocaleDateString('en-US', {month:'short', day:'numeric', year:'numeric'});
}

function blogCardHTML(p, prefix){
  prefix = prefix || '';
  const dateLabel = formatDate(p.date);
  const safeAlt = (p.imageAlt || p.title).replace(/"/g, '&quot;');
  // NOTE: this fallback markup ends up INSIDE a double-quoted onerror="..."
  // HTML attribute, so it must use single quotes for its own attribute
  // (class='...') — double quotes here would prematurely close onerror
  // and break the tag.
  const fallbackIcon = `<span class='blog-thumb-icon'>${p.icon}</span>`;
  const thumbInner = p.image
    ? `<img src="${prefix}${p.image}" alt="${safeAlt}" loading="lazy" onerror="this.parentElement.innerHTML='${fallbackIcon.replace(/'/g, "\\'")}';"/>`
    : fallbackIcon;

  const metaLine = p.published
    ? `${p.readMins} min read · ${dateLabel}`
    : `${p.readMins} min read · ${dateLabel} · Coming soon`;

  const inner = `
    <div class="blog-thumb">${thumbInner}</div>
    <div class="blog-body">
      <span class="blog-cat">${p.category.toUpperCase()}</span>
      <h4>${p.title}</h4>
      <p class="blog-excerpt">${p.excerpt}</p>
      <div class="blog-meta">${metaLine}</div>
    </div>`;

  if (!p.published) {
    return `<div class="blog-card blog-card-disabled">${inner}</div>`;
  }
  return `<a class="blog-card" href="${prefix}blog/${p.slug}.html">${inner}</a>`;
}
