#!/usr/bin/env python3
"""
scripts/update_blog_data.py
============================
Regenerates the BLOG_POSTS array inside assets/js/blog-data.js by reading
metadata out of an `<!-- FX:POST ... FX:POST -->` comment block placed
inside each file in /blog/*.html (non-recursive — this MUST stay in sync
with the workflow's `paths: blog/*.html` filter and its own glob below).

WHAT IT DOES
------------
1. Finds every /blog/*.html file (top level only).
2. Reads its FX:POST metadata block.
3. Builds a fresh BLOG_POSTS array, sorted by date (newest first).
4. Splices that array back into assets/js/blog-data.js, leaving everything
   below it (formatDate, escapeHtml, blogCardHTML) exactly as it is on
   disk — so hand edits to those functions are never clobbered.

FX:POST BLOCK FORMAT
---------------------
Put this as an HTML comment anywhere in a post file, e.g. in <head>:

    <!-- FX:POST
    slug: my-post-slug
    title: My Post Title
    category: Guide
    icon: 📣
    image: assets/images/blog/my-post-slug.webp
    imageAlt: Alt text for the thumbnail
    excerpt: One or two sentence teaser shown on the card.
    readMins: 8
    date: 2026-09-01
    published: true
    featured: false
    author: Prashant Lalwani
    FX:POST -->

Required fields: title, date.
Everything else falls back to a sane default — see DEFAULTS below:
  - slug        -> the filename without ".html" (e.g. my-post.html -> "my-post")
  - image       -> assets/images/blog/<slug>.webp
  - imageAlt    -> same as title
  - category    -> "Guide"
  - icon        -> "📝"
  - excerpt     -> ""
  - readMins    -> 5
  - published   -> true
  - featured    -> false
  - author      -> "Prashant Lalwani"

A file with no FX:POST block at all is skipped with a warning (handy for
drafts, or non-post pages that happen to live in /blog/). A file whose
FX:POST block is missing a required field is also skipped, with an error
logged so it's obvious in the Actions log — but it will NOT fail the whole
workflow run, so one bad post can't block everyone else's posts from
publishing.
"""

import glob
import json
import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Single star, non-recursive — must match the workflow's `blog/*.html` path filter.
BLOG_GLOB = os.path.join(REPO_ROOT, "blog", "*.html")
OUTPUT_JS = os.path.join(REPO_ROOT, "assets", "js", "blog-data.js")

FX_BLOCK_RE = re.compile(r"<!--\s*FX:POST(.*?)FX:POST\s*-->", re.DOTALL)

BOOL_FIELDS = {"published", "featured"}
REQUIRED_FIELDS = ("title", "date")

DEFAULTS = {
    "category": "Guide",
    "icon": "📝",
    "excerpt": "",
    "readMins": 5,
    "published": True,
    "featured": False,
    "author": "Prashant Lalwani",
}

HEADER_COMMENT = """/* Flexora.Ai — auto-generated by scripts/update_blog_data.py
   DO NOT edit BLOG_POSTS by hand — add/remove files in /blog/ instead,
   each with an <!-- FX:POST ... --> block, and push. This file rewrites
   itself automatically. blogCardHTML() and formatDate() below are safe
   to hand-edit if you want to change how a card looks. */
"""

# Used only if assets/js/blog-data.js doesn't exist yet (first-ever run).
# On every later run, whatever is already on disk below the BLOG_POSTS
# array — including any hand edits — is preserved verbatim instead.
FALLBACK_HELPERS = r'''function formatDate(d){
  return new Date(d + 'T00:00:00').toLocaleDateString('en-US', {month:'short', day:'numeric', year:'numeric'});
}

// Escapes text that gets inserted into HTML via innerHTML/template strings,
// so a title or excerpt containing <, >, &, or " can never break card markup
// or be mistaken for real HTML. Used for anything NOT already inside an
// HTML attribute (those use their own quote-only escaping below).
function escapeHtml(str){
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function blogCardHTML(p, prefix){
  prefix = prefix || '';
  const dateLabel = formatDate(p.date);
  const safeAlt = escapeHtml(p.imageAlt || p.title).replace(/"/g, '&quot;');
  const safeTitle = escapeHtml(p.title);
  const safeExcerpt = escapeHtml(p.excerpt);
  const safeCategory = escapeHtml(p.category.toUpperCase());
  // NOTE: this fallback markup ends up INSIDE a double-quoted onerror="..."
  // HTML attribute, so it must use single quotes for its own attribute
  // (class='...') — double quotes here would prematurely close onerror
  // and break the tag.
  const fallbackIcon = `<span class='blog-thumb-icon'>${p.icon}</span>`;
  const thumbInner = p.image
    ? `<img src="${prefix}${p.image}" alt="${safeAlt}" loading="lazy" onerror="this.parentElement.innerHTML='${fallbackIcon.replace(/'/g, "\\'")}';"/>`
    : fallbackIcon;

  const safeAuthor = escapeHtml(p.author || 'Prashant Lalwani');
  const metaLine = p.published
    ? `${p.readMins} min read · ${dateLabel} · <span class="blog-byline">${safeAuthor}</span>`
    : `${p.readMins} min read · ${dateLabel} · Coming soon`;

  const inner = `
    <div class="blog-thumb">${thumbInner}</div>
    <div class="blog-body">
      <span class="blog-cat">${safeCategory}</span>
      <h4>${safeTitle}</h4>
      <p class="blog-excerpt">${safeExcerpt}</p>
      <div class="blog-meta">${metaLine}</div>
    </div>`;

  if (!p.published) {
    return `<div class="blog-card blog-card-disabled">${inner}</div>`;
  }
  return `<a class="blog-card" href="${prefix}blog/${p.slug}.html">${inner}</a>`;
}
'''


def parse_fx_block(text, filename):
    match = FX_BLOCK_RE.search(text)
    if not match:
        print(f"::warning::Skipping {os.path.relpath(filename, REPO_ROOT)} — no <!-- FX:POST ... FX:POST --> block found.")
        return None

    fields = {}
    for line in match.group(1).splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()

    missing = [f for f in REQUIRED_FIELDS if not fields.get(f)]
    if missing:
        print(f"::error::{os.path.relpath(filename, REPO_ROOT)}: FX:POST block is missing required field(s): "
              f"{', '.join(missing)}. Skipping this post.")
        return None

    return fields


def build_post(fields, filename):
    slug = fields.get("slug") or os.path.splitext(os.path.basename(filename))[0]
    title = fields["title"]

    post = {
        "slug": slug,
        "title": title,
        "category": fields.get("category", DEFAULTS["category"]),
        "icon": fields.get("icon", DEFAULTS["icon"]),
        "image": fields.get("image") or f"assets/images/blog/{slug}.webp",
        "imageAlt": fields.get("imageAlt") or title,
        "excerpt": fields.get("excerpt", DEFAULTS["excerpt"]),
        "readMins": DEFAULTS["readMins"],
        "date": fields["date"],
        "published": DEFAULTS["published"],
        "featured": DEFAULTS["featured"],
        "author": fields.get("author", DEFAULTS["author"]),
    }

    if "readMins" in fields:
        try:
            post["readMins"] = int(fields["readMins"])
        except ValueError:
            print(f"::warning::{os.path.relpath(filename, REPO_ROOT)}: readMins "
                  f"'{fields['readMins']}' isn't a whole number, defaulting to {DEFAULTS['readMins']}.")

    for flag in BOOL_FIELDS:
        if flag in fields:
            post[flag] = fields[flag].strip().lower() in ("true", "yes", "1")

    return post


def js_object_literal(post):
    # json.dumps handles all string quoting/escaping for us (including the
    # emoji in icon); keys are left unquoted to match the existing style.
    parts = [f"{key}:{json.dumps(value, ensure_ascii=False)}" for key, value in post.items()]
    return "{ " + ", ".join(parts) + " }"


def build_array_block(posts):
    posts_sorted = sorted(posts, key=lambda p: p["date"], reverse=True)
    lines = ["const BLOG_POSTS = ["]
    for post in posts_sorted:
        lines.append(f"  {js_object_literal(post)},")
    lines.append("];")
    return "\n".join(lines)


def read_existing_helpers():
    """Return whatever text currently sits below the BLOG_POSTS array, so
    hand edits to formatDate/escapeHtml/blogCardHTML survive every run."""
    if not os.path.exists(OUTPUT_JS):
        return FALLBACK_HELPERS

    with open(OUTPUT_JS, "r", encoding="utf-8") as f:
        existing = f.read()

    # First "];" that sits alone on its own line closes the BLOG_POSTS
    # array — everything after that is the hand-editable helper code.
    match = re.search(r"^\];\s*\n(.*)", existing, re.DOTALL | re.MULTILINE)
    if match and match.group(1).strip():
        return match.group(1)
    return FALLBACK_HELPERS


def main():
    files = sorted(glob.glob(BLOG_GLOB))
    if not files:
        print("No files found under /blog/*.html — nothing to do.")

    posts = []
    for filename in files:
        with open(filename, "r", encoding="utf-8") as f:
            content = f.read()
        fields = parse_fx_block(content, filename)
        if fields is None:
            continue
        posts.append(build_post(fields, filename))

    array_block = build_array_block(posts)
    helpers = read_existing_helpers()

    output = f"{HEADER_COMMENT}\n{array_block}\n\n{helpers}"
    if not output.endswith("\n"):
        output += "\n"

    os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"Wrote {len(posts)} post(s) to {os.path.relpath(OUTPUT_JS, REPO_ROOT)}")


if __name__ == "__main__":
    main()
